In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv('buy_car.csv')
ds.head()

Montly Salary  age  Y/N
0           2386   18    0
1           2486   19    0
2           2586   20    0
3           2686   20    0
4           2756   20    0

In [3]:
ds.shape

(400, 3)

In [4]:
x = ds.iloc[:, :-1].values
y = ds.iloc[:, 2].values

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

## Use Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression # change according to model
classifier = LogisticRegression(random_state = 0) # change according to model
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

---

## Predict

In [8]:
y_pred = classifier.predict(x_test)

---

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[47,  2],
       [ 8, 43]], dtype=int64)

In [12]:
y_test, y_pred

(array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64))

In [13]:
from sklearn.metrics import accuracy_score
AR = accuracy_score(y_test, y_pred)
print(AR)

0.9


In [14]:
# Predicting a value salary=15000 and age=21
y_pred_new=classifier.predict(sc_x.transform([[15000,21]]))
print(y_pred_new)

[0]


0 means No.