In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv('play.csv')
ds.head()

outlook temperature humidity  windy Play(Y/N)
0   Sunny         Hot     High  False        No
1   Sunny         Hot     High   True        No
2   Rainy        Mild     High  False       Yes
3   Rainy        Cool   Normal  False       Yes
4   Rainy        Cool   Normal   True        No

In [3]:
ds.shape

(10, 5)

In [4]:
x = ds.iloc[:,:-1].values
y = ds.iloc[:,4].values

In [5]:
# Sorting
i = 0 
for i in range(0,4):
    d = list(set(ds.iloc[:,i].values))
    d.sort()
    print(i,d)
    i += 1

0 ['Rainy', 'Sunny']
1 ['Cool', 'Hot', 'Mild']
2 ['High', 'Normal']
3 [False, True]


## Label Encoder

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:,0] = labelencoder_X.fit_transform(x[:,0])
x[:,1] = labelencoder_X.fit_transform(x[:,1])
x[:,2] = labelencoder_X.fit_transform(x[:,2])
x[:,3] = labelencoder_X.fit_transform(x[:,3])
print(x)

[[1 1 0 0]
 [1 1 0 1]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 0]
 [1 0 1 0]
 [0 2 1 0]
 [1 2 1 1]
 [0 2 0 1]]


## Use Naive Bayes

In [7]:
from sklearn.naive_bayes import GaussianNB # Use for categorical data
classifier = GaussianNB()
classifier = classifier.fit(x,y)

In [8]:
prediction = classifier.predict([[1, 0, 0, 0]])
# sunny : 1
# cool temperature: 0
# humidity high: 0
# windy False: 0

print(prediction)

['No']


In [9]:
prediction = classifier.predict([[1, 2, 1, 1]])
# sunny : 1
# mild temperature: 2
# humidity normal: 1 
# windy True: 1

print(prediction)

['No']
